const STRINGS = {
  ja: {
    navProducts: "商品一覧", navCustomize: "カスタマイズ", navAbout: "私たちについて", navCart: "カート", language: "English",
    footerIntro: "一輪ずつ手で仕立てる、あなただけのシルクフラワー。色と想いをかたちにします。", footerGuide: "ご利用ガイド", footerContact: "お問い合わせ", privacy: "プライバシーポリシー", terms: "利用規約", returns: "返品・キャンセル", shipping: "配送について", commerce: "特定商取引法に基づく表記",
    homeEyebrow: "手作りの花、あなたの色に。", homeTitle: "一輪ずつ、想いを込めて", homeLead: "好きな花を、好きな数だけ。あなたのための組み合わせを一緒に仕立てます。", startCustomize: "カスタマイズを始める", explore: "商品を見る", productsEyebrow: "Collection", productEntrances: "商品コレクション", productIntro: "10のベースから、花材と仕上げを自由にお選びいただけます。", from: "〜", customize: "カスタマイズする", storyEyebrow: "Our craft", storyTitle: "手仕事の時間を、花の記憶へ", storyBody1: "2008年から培ってきた造花づくりの経験をもとに、花びらの重なりや茎の表情まで丁寧に仕立てています。", storyBody2: "ご注文後にスタッフが内容を確認し、色合わせや制作についてご連絡します。写真とまったく同じものではなく、手仕事ならではの個性をお楽しみください。", storyPoint1: "16年以上の制作経験", storyPoint2: "一品ずつ手作業で確認", storyPoint3: "日本向けに丁寧に梱包",
    allProducts: "すべて", support: "応援グッズ", bouquet: "ブーケ", corsage: "コサージュ", accessory: "アクセサリー", wear: "ウェア", productList: "商品一覧", productListLead: "ベース商品を選んで、お好みの花材と仕上げを組み合わせてください。", detailMaterial: "素材", detailSize: "サイズ・仕様", detailWeight: "商品重量", detailScene: "おすすめシーン", unavailable: "現在カスタマイズできません", retry: "もう一度試す",
    chooseFlowers: "花材を選ぶ", selectedKinds: "{count}種類選択中", searchFlowers: "花材名で検索", clear: "クリア", noResults: "条件に合う花材がありません。", add: "追加", remove: "削除", soldOut: "在庫切れ", rose: "バラ系", peony: "牡丹・芍薬系", accent: "アレンジフラワー", greenery: "グリーン・枝物", maxReached: "この商品の花材上限に達しました。", flowerLimit: "1種類につき最大{max}点、合計{total}点まで選べます。", wrappingOptions: "包装・オプション", wrappingPaper: "ラッピング紙", ribbon: "リボン", messageCard: "メッセージカード", none: "なし", yesWithPrice: "あり（+{price}）", notes: "注意事項", notesBody: "受注制作のため、お届けまで通常2〜4週間ほどかかります。画面と実物では色味が異なる場合があります。カスタマイズ商品は原則として返品・交換を承れません。輸送時の軽微な形崩れは整えてご使用ください。在庫状況により、印象を損なわない同等花材をご提案する場合があります。", composition: "現在の組み合わせ", imageReference: "表示画像は完成イメージです。実際の配置や色味とは異なる場合があります。", basePrice: "商品基本価格", flowerSubtotal: "追加花材", options: "包装・オプション", itemSubtotal: "商品小計", weight: "推定重量", shippingEstimate: "配送料目安", quoteRequired: "個別見積", estimatedTotal: "お見積合計", addToCart: "カートに追加", added: "カートに追加しました", selectOne: "花材を1点以上選んでください。", taxIncluded: "税込・概算", inquiryOnly: "この時点では課金されません。", backProducts: "商品一覧へ戻る",
    cartTitle: "ショッピングカート", itemsCount: "{count}点", edit: "カスタマイズを変更", quantity: "商品数量", cartEmpty: "カートは空です", goProducts: "商品一覧へ", shippingOver: "500gを超えるため、送料は注文確認後にご案内します。", subtotal: "小計", total: "合計目安", checkout: "お届け先の入力へ", cartChanged: "別のタブでカートが更新されました。", invalidRemoved: "販売終了または不正な商品をカートから除外しました。",
    checkoutTitle: "お届け先と注文内容", orderDetails: "注文内容", deliveryDetails: "お届け先情報", fullName: "お名前", furigana: "フリガナ", phone: "電話番号", postal: "郵便番号", address: "住所", email: "メールアドレス", remarks: "備考", optional: "任意", required: "必須", submitOrder: "注文内容を送信する", noCharge: "※この時点ではまだ課金されません。注文確認後、担当者よりご連絡いたします。", submitFailed: "送信できませんでした。通信状況を確認して、もう一度お試しください。", emptyCheckout: "カートに商品がありません。", validationRequired: "入力してください。", validationEmail: "メールアドレスの形式を確認してください。", validationPhone: "電話番号を10〜11桁で入力してください。", validationPostal: "郵便番号を7桁で入力してください。", validationKana: "全角カタカナで入力してください。", sending: "送信中…",
    completeTitle: "ご注文リクエストを受け付けました", completeLead: "内容を確認のうえ、担当者より2営業日以内にご連絡します。まだお支払いは発生していません。", orderNumber: "受付番号", submittedAt: "受付日時", nextSteps: "今後の流れ", step1: "内容と在庫をスタッフが確認", step2: "メールで仕様と最終金額をご案内", step3: "ご同意・お支払い後に制作開始", home: "ホームへ戻る",
    aboutThisPage: "ご案内", legalDraft: "このページは公開前の確認用ひな形です。実際の運営事業者情報と法務確認済みの内容に差し替えてください。"
  },
  en: {
    navProducts: "Shop", navCustomize: "Customize", navAbout: "Our Story", navCart: "Cart", language: "日本語",
    footerIntro: "Silk flowers arranged by hand, one stem at a time. We turn your colours and feelings into something personal.", footerGuide: "Customer care", footerContact: "Contact", privacy: "Privacy Policy", terms: "Terms of Use", returns: "Returns & Cancellations", shipping: "Shipping", commerce: "Seller Information",
    homeEyebrow: "Handmade flowers, in your colours.", homeTitle: "Every flower, made with feeling", homeLead: "Choose the flowers and the number you love. We will shape your personal composition together.", startCustomize: "Start customizing", explore: "Explore the collection", productsEyebrow: "Collection", productEntrances: "Our flower collection", productIntro: "Start with one of ten designs, then choose your flowers and finishing details.", from: "from", customize: "Customize", storyEyebrow: "Our craft", storyTitle: "Handcrafting memories in flowers", storyBody1: "Drawing on our artificial-flower craft since 2008, we carefully shape every layer of petals and every stem.", storyBody2: "After you submit your request, our team reviews your colours and specifications with you. Each handmade piece has its own character and will not be an exact copy of the reference image.", storyPoint1: "Over 16 years of craft", storyPoint2: "Every piece checked by hand", storyPoint3: "Carefully packed for Japan",
    allProducts: "All", support: "Fan goods", bouquet: "Bouquets", corsage: "Corsages", accessory: "Accessories", wear: "Wear", productList: "Products", productListLead: "Choose a base design, then combine the flowers and finishing details you love.", detailMaterial: "Material", detailSize: "Size & specifications", detailWeight: "Product weight", detailScene: "Recommended for", unavailable: "Customization unavailable", retry: "Try again",
    chooseFlowers: "Choose your flowers", selectedKinds: "{count} selected", searchFlowers: "Search flowers", clear: "Clear", noResults: "No flowers match your search.", add: "Add", remove: "Remove", soldOut: "Sold out", rose: "Roses", peony: "Peonies", accent: "Accent flowers", greenery: "Greenery & stems", maxReached: "You have reached the flower limit for this item.", flowerLimit: "Choose up to {max} of each flower and {total} flowers in total.", wrappingOptions: "Wrapping & options", wrappingPaper: "Wrapping paper", ribbon: "Ribbon", messageCard: "Message card", none: "None", yesWithPrice: "Add (+{price})", notes: "Important notes", notesBody: "Made-to-order pieces usually take 2–4 weeks. Colours may look different in person. Customized goods generally cannot be returned or exchanged. Minor movement in transit can be gently reshaped. If a flower is unavailable, we may suggest a close substitute that preserves the overall look.", composition: "Your composition", imageReference: "The image is for reference. Actual placement and colours may vary.", basePrice: "Base product price", flowerSubtotal: "Additional flowers", options: "Wrapping & options", itemSubtotal: "Item subtotal", weight: "Estimated weight", shippingEstimate: "Estimated shipping", quoteRequired: "Quote required", estimatedTotal: "Estimated total", addToCart: "Add to cart", added: "Added to cart", selectOne: "Choose at least one flower.", taxIncluded: "Tax included · Estimate", inquiryOnly: "You will not be charged at this stage.", backProducts: "Back to products",
    cartTitle: "Shopping cart", itemsCount: "{count} items", edit: "Edit customization", quantity: "Item quantity", cartEmpty: "Your cart is empty", goProducts: "View products", shippingOver: "Shipping will be confirmed after review because the order exceeds 500g.", subtotal: "Subtotal", total: "Estimated total", checkout: "Enter delivery details", cartChanged: "Your cart was updated in another tab.", invalidRemoved: "Unavailable or invalid items were removed from your cart.",
    checkoutTitle: "Delivery & order details", orderDetails: "Order details", deliveryDetails: "Delivery details", fullName: "Full name", furigana: "Name in Katakana", phone: "Phone", postal: "Postal code", address: "Address", email: "Email", remarks: "Notes", optional: "Optional", required: "Required", submitOrder: "Submit order request", noCharge: "You will not be charged at this stage. Our team will contact you after reviewing the request.", submitFailed: "We could not submit your request. Check your connection and try again.", emptyCheckout: "There are no items in your cart.", validationRequired: "Please complete this field.", validationEmail: "Enter a valid email address.", validationPhone: "Enter a 10–11 digit phone number.", validationPostal: "Enter a 7-digit Japanese postal code.", validationKana: "Enter the name in full-width Katakana.", sending: "Sending…",
    completeTitle: "Your order request has been received", completeLead: "Our team will review it and contact you within two business days. No payment has been taken.", orderNumber: "Request number", submittedAt: "Submitted", nextSteps: "What happens next", step1: "We check your selections and availability", step2: "We email you the final specification and price", step3: "Production starts after your approval and payment", home: "Return home",
    aboutThisPage: "Information", legalDraft: "This page is a pre-launch template. Replace it with verified operator information and legally reviewed content before publishing."
  }
};

const KEY = "yanohana-language";
export const getLanguage = () => {
  try { return localStorage.getItem(KEY) === "en" ? "en" : "ja"; }
  catch { return document.documentElement.lang === "en" ? "en" : "ja"; }
};
export const t = (key, vars = {}) => {
  let value = STRINGS[getLanguage()][key] ?? STRINGS.ja[key] ?? key;
  return Object.entries(vars).reduce((text, [name, replacement]) => text.replaceAll(`{${name}}`, replacement), value);
};
export const localized = (item, field) => getLanguage() === "en" ? (item[`${field}En`] || item[`${field}Ja`] || "") : (item[`${field}Ja`] || "");
export function setLanguage(language) {
  try { localStorage.setItem(KEY, language === "en" ? "en" : "ja"); }
  catch { document.documentElement.lang = language === "en" ? "en" : "ja"; }
  document.documentElement.lang = getLanguage();
  window.dispatchEvent(new CustomEvent("languagechange"));
}
export function applyTranslations(scope = document) {
  document.documentElement.lang = getLanguage();
  scope.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = t(node.dataset.i18n); });
  scope.querySelectorAll("[data-i18n-placeholder]").forEach((node) => { node.placeholder = t(node.dataset.i18nPlaceholder); });
}
